[package]
name = "pubsub-common"
version = "0.1.0"
authors = ["Jack O'Sullivan <jackos1998@gmail.com>"]

[dependencies]
quick-error = "~1.2"
log = "~0.4"
byteorder = "~1.2"
enum_primitive = "~0.1"
crossbeam-channel = "~0.2"
priority-queue = "~0.5"

[dev-dependencies]
lazy_static = "~1.1"
