[package]
name = "pubsub-common"
version = "0.1.0"
authors = ["Jack O'Sullivan <jackos1998@gmail.com>"]

[dependencies]
enum_primitive = "~0.1"
quick-error = "~1.2"
log = "~0.4"
bytes = "~0.4"
crossbeam-channel = "~0.2"
priority-queue = "~0.5"
