[package]
name = "pubsub-client"
version = "0.1.0"
authors = ["Jack O'Sullivan <jackos1998@gmail.com>"]

[dependencies]
quick-error = "~1.2"
debug_stub_derive = "~0.3"
log = "~0.4"
bytes = "~0.4"
crossbeam = "~0.5"
pubsub-common = { path = "../pubsub-common" }
